name: Force-sync from Gitee

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  force-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add Gitee remote
        run: git remote add gitee https://gitee.com/zhigan/rh_helper.git

      - name: Force overwrite GitHub with Gitee
        run: |
          git checkout master
          git fetch gitee master
          git reset --hard gitee/master
          git push --force origin master
